dataset:
  imagenet_path: ./data/imagenet
optimizer:
  optimizer: sgd
  lr: 0.01
  lr_scheduler: reduce_on_plateau
  lr_scheduler_args:
    mode: max
    factor: 0.5
    patience: 4
    threshold: 0.001
    threshold_mode: abs
    min_lr: 0.0005
model:
  model_path: ./models/imagenet/resnet18/ceiling/4.0x/model_4_compressed_layers_post.ckpt
  existing_sketch_dicts:
    layer1:
    - !!python/tuple
      - 0
      - conv1: !!python/tuple
        - 64
        - 16
    - !!python/tuple
      - 0
      - conv2: !!python/tuple
        - 64
        - 16
    - !!python/tuple
      - 1
      - conv1: !!python/tuple
        - 64
        - 16
    - !!python/tuple
      - 1
      - conv2: !!python/tuple
        - 64
        - 16
  sketch_dicts:
    layer2:
    - !!python/tuple
      - 0
      - conv1: !!python/tuple
        - 64
        - 16
  unfreeze_all_sketches: true
  freeze_model: true
  sketch_init: default
  sketch_type: post_act
  batchnorm: false
train:
  save_model: true
  save_dir: ./models/imagenet/resnet18/ceiling/4.0x/
  model_filename: model_5_compressed_layers_post
  log_dir: ./logs/resnet18/ceiling/4.0x/
  version: 0
  num_gpus: 8
  batch_size: 256
  num_workers: 10
  epochs: 4
  target_accuracy: 70.0
evaluate:
  batch_size: 256
seed: 99
